"""Vendor public key used to verify license keys.

This file is generated by ``python tools/license_admin.py init``.  It only ever
holds the PUBLIC half of the signing key, so it is safe to ship inside the
application.  The matching private key lives in ``vendor_keys/`` on the
vendor's own machine and must never be distributed.

Until ``init`` has been run this value is empty and every license check fails
with a clear "no public key" message.
"""

PUBLIC_KEY_B64 = 'MtbtcpAWWTM4HTF0DoZI3868-jYA7QZ6aNDj9luih70'
