"""Build the Windows executable (Phase 5): PyInstaller over the Phase 4 tree.

Consumes the obfuscated product source tree from ``build/product/`` (see
``tools/build_product.py``) and produces a clean desktop target:

    build/exe/SchoolManager/SchoolManager.exe     (onedir, windowed)

Bundling notes:
* The **PyArmor runtime package** (``pyarmor_runtime_000000``) is included as a
  hidden import so its ``.pyd`` travels with the bundle; every obfuscated
  ``app`` module is also listed explicitly, because PyInstaller cannot see
  imports inside PyArmor-encrypted module bodies.
* Third-party packages are hidden imports for the same reason; their own
  transitive dependencies are then analysed normally by PyInstaller hooks.
* Templates and static (offline vendor) assets are data files loaded at
  runtime from the bundle.
* The exe is windowed (``console=False``); the launcher redirects its streams
  to ``<data folder>/school_manager.log`` (see ``school_manager.pyw``).

Verification (after the build): the exe is started with ``--selftest`` against
a scratch data folder - it probes healthz/login/vendor assets and asserts that
a fresh install is gated to the license page (enforcement is forced on in the
packaged exe).  A second run WITHOUT the scratch folder proves the data
folder defaults to ``%LOCALAPPDATA%\\SchoolManager``.

Usage:
    python tools/build_exe.py                 # build + verify
    python tools/build_exe.py --no-verify     # build only
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.request
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PRODUCT_ROOT = PROJECT_ROOT / 'build' / 'product'
EXE_DIST = PROJECT_ROOT / 'build' / 'exe'
PYINSTALLER_WORK = PROJECT_ROOT / 'build' / 'pyinstaller'

APP_NAME = 'SchoolManager'

#: Runtime dependencies that PyInstaller cannot discover from the obfuscated
#: modules (their import lists are encrypted).  Everything transitive below
#: these is analysed normally once the package itself is included.
#: reportlab subpackages are imported lazily inside functions (QR codes on ID
#: cards), so they are enumerated explicitly.
THIRD_PARTY_HIDDEN_IMPORTS = [
    'flask', 'flask_sqlalchemy', 'flask_login', 'waitress', 'jinja2',
    'werkzeug', 'sqlalchemy', 'pandas', 'openpyxl', 'reportlab', 'PIL',
    'cryptography', 'requests',
    'reportlab.graphics', 'reportlab.graphics.barcode',
    'reportlab.graphics.barcode.qr', 'reportlab.graphics.shapes',
    'reportlab.lib.pagesizes', 'reportlab.lib.styles', 'reportlab.lib.units',
    'reportlab.lib.utils', 'reportlab.pdfgen', 'reportlab.platypus',
]

VERIFY_PORT_BASE = 8800


def collect_app_modules(product_root=PRODUCT_ROOT):
    """Every ``app.*`` module in the obfuscated tree, plus the runtime package."""
    modules = []
    app_dir = Path(product_root) / 'app'
    for path in sorted(app_dir.rglob('*.py')):
        rel = path.relative_to(app_dir)
        parts = list(rel.with_suffix('').parts)
        if parts[-1] == '__init__':
            parts = parts[:-1]
        modules.append('.'.join(['app'] + parts))
    return modules + ['pyarmor_runtime_000000']


#: Optional heavy packages whose *optional* import chains (pandas accelerators,
#: plotting backends, ML ecosystems pulled via package metadata) must never
#: reach the bundle — the application never uses them.
EXCLUDED_PACKAGES = [
    'torch', 'transformers', 'onnxruntime', 'scipy', 'pyarrow', 'sklearn',
    'matplotlib', 'jedi', 'IPython', 'pytest',
]


def collect_datas(product_root=PRODUCT_ROOT):
    """Runtime data folders: Jinja templates + the offline static assets."""
    product_root = Path(product_root)
    return [
        (str(product_root / 'app' / 'templates'), 'app/templates'),
        (str(product_root / 'app' / 'static'), 'app/static'),
    ]


def generate_spec(product_root=PRODUCT_ROOT, name=APP_NAME):
    """Render the PyInstaller spec (pure; unit-tested)."""
    product_root = Path(product_root).resolve()
    hiddenimports = collect_app_modules(product_root) + THIRD_PARTY_HIDDEN_IMPORTS
    datas = collect_datas(product_root)

    def py_list(entries):
        return '[' + ', '.join(repr(entry) for entry in entries) + ']'

    def data_list(entries):
        return '[' + ', '.join(f'({src!r}, {dst!r})' for src, dst in entries) + ']'

    return (
        "# Auto-generated by tools/build_exe.py - do not edit by hand.\n"
        f"# Bundles the obfuscated product tree: {product_root}\n"
        "from PyInstaller.utils.hooks import collect_submodules\n"
        f"hiddenimports = {py_list(hiddenimports)}\n"
        "# reportlab's barcode package imports its siblings dynamically by\n"
        "# name at import time - collect the whole subpackage.\n"
        "hiddenimports = hiddenimports + "
        "collect_submodules('reportlab.graphics.barcode')\n"
        "a = Analysis(\n"
        f"    [{str(product_root / 'school_manager.pyw')!r}],\n"
        f"    pathex={py_list([str(product_root)])},\n"
        "    binaries=[],\n"
        f"    datas={data_list(datas)},\n"
        "    hiddenimports=hiddenimports,\n"
        "    hookspath=[],\n"
        "    hooksconfig={},\n"
        "    runtime_hooks=[],\n"
        f"    excludes={py_list(EXCLUDED_PACKAGES)},\n"
        "    noarchive=False,\n"
        ")\n"
        "pyz = PYZ(a.pure)\n"
        "exe = EXE(\n"
        "    pyz,\n"
        "    a.scripts,\n"
        "    exclude_binaries=True,\n"
        f"    name={name!r},\n"
        "    debug=False,\n"
        "    strip=False,\n"
        "    upx=False,\n"
        "    console=False,\n"
        "    icon=None,\n"
        ")\n"
        "coll = COLLECT(\n"
        "    exe,\n"
        "    a.binaries,\n"
        "    a.datas,\n"
        f"    name={name!r},\n"
        ")\n"
    )


def _refresh_toplevel_files(product_root=PRODUCT_ROOT):
    """The product tree copies of launcher/requirements must match the
    project's current versions (the Phase 4 build may be older)."""
    product_root = Path(product_root)
    for entry in ('school_manager.pyw', 'requirements.txt'):
        source = PROJECT_ROOT / entry
        if source.is_file():
            shutil.copy2(source, product_root / entry)


def build_exe(output_dist=EXE_DIST, product_root=PRODUCT_ROOT):
    _refresh_toplevel_files(product_root)
    spec_path = PROJECT_ROOT / 'build' / f'{APP_NAME}.spec'
    spec_path.parent.mkdir(parents=True, exist_ok=True)
    spec_path.write_text(generate_spec(product_root), encoding='utf-8')
    print(f'Spec written: {spec_path}')

    result = subprocess.run(
        [sys.executable, '-m', 'PyInstaller', '--noconfirm',
         '--distpath', str(output_dist), '--workpath', str(PYINSTALLER_WORK),
         str(spec_path)],
        capture_output=True, text=True, cwd=str(PROJECT_ROOT))
    if result.returncode != 0:
        raise RuntimeError(f'PyInstaller failed:\n{result.stdout[-4000:]}\n'
                           f'{result.stderr[-4000:]}')
    exe_path = Path(output_dist) / APP_NAME / f'{APP_NAME}.exe'
    if not exe_path.is_file():
        raise RuntimeError(f'exe missing after build: {exe_path}')
    print(f'Built: {exe_path}')
    return exe_path


def run_selftest(exe_path, env_overrides=None, expect_verify=True, timeout=180):
    """Run ``SchoolManager.exe --selftest`` and return its output."""
    env = dict(os.environ)
    env.setdefault('AUTO_BACKUP_ENABLED', '0')
    if env_overrides:
        env.update(env_overrides)
    result = subprocess.run([str(exe_path), '--selftest'],
                            capture_output=True, text=True, timeout=timeout,
                            env=env, cwd=str(exe_path.parent))
    output = (result.stdout or '') + (result.stderr or '')
    if expect_verify and 'VERIFY-PASS' not in output:
        raise RuntimeError(f'selftest failed (rc={result.returncode}):\n'
                           f'{output[-3000:]}')
    return output


def verify_bundled_exe(exe_path):
    """Phase 5 acceptance checks on the packaged executable."""
    # 1. Core routes, offline assets and forced license enforcement, on a
    #    scratch data folder so the developer's machine stays untouched.
    scratch = tempfile.mkdtemp(prefix='p5-verify-')
    try:
        port = str(_free_verify_port())
        output = run_selftest(exe_path, env_overrides={
            'SCHOOL_DATA_DIR': scratch,
            'PORT': port,
        })
        print(output.strip().splitlines()[-1])
    finally:
        shutil.rmtree(scratch, ignore_errors=True)

    # 2. Data-folder rule (see verify_default_data_folder).
    verify_default_data_folder(exe_path)
    return True


def verify_default_data_folder(exe_path):
    """With no overrides the exe must create and use the per-school data
    folder (``%LOCALAPPDATA%\\SchoolManager``): database + log file inside.

    SAFETY: if that folder already exists, this machine carries real
    installed-product data (database, license, WhatsApp session, backups) —
    never delete it.  The check only runs where the folder is absent, so the
    finally-cleanup below removes only what this check itself created.
    """
    local_data = Path(os.environ.get('LOCALAPPDATA') or
                      (Path.home() / 'AppData' / 'Local')) / 'SchoolManager'
    if local_data.exists():
        print(f'SKIPPED default data-folder check: {local_data} already exists '
              'and may hold real data. Run it on a machine without School '
              'Manager installed (or rename that folder) to include this check.')
        return True
    try:
        port = str(_free_verify_port())
        run_selftest(exe_path, env_overrides={'PORT': port})
        assert (local_data / 'school.db').is_file(), \
            f'database not created in {local_data}'
        assert (local_data / 'school_manager.log').is_file(), \
            f'log file missing in {local_data}'
        print(f'Data folder verified: {local_data}')
    finally:
        shutil.rmtree(local_data, ignore_errors=True)
    return True


def _free_verify_port():
    import socket
    with socket.socket() as sock:
        sock.bind(('127.0.0.1', 0))
        return sock.getsockname()[1]


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--no-verify', action='store_true',
                        help='build only; skip the bundled smoke tests')
    args = parser.parse_args(argv)

    if not (PRODUCT_ROOT / 'app').is_dir():
        print('build/product missing - running the Phase 4 build first...')
        from build_product import main as build_product_main
        build_product_main([])

    exe_path = build_exe()
    if not args.no_verify:
        print('Verifying the bundled executable...')
        verify_bundled_exe(exe_path)
        print('Phase 5 verification passed.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
